name: Build and run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'

permissions:
  contents: read

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      uses: nick-fields/retry@v2.8.3
      env:
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      with:
        timeout_minutes: 30
        retry_on: error
        max_attempts: 5
        command: ./run.sh
