name: Run and insert into database
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Run and insert into database
      env:
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        ./run.sh
